### ISSUE TITLE
GXParser DOMParser  issues

### ISSUE THREAD

**Issue by isabolic** [jimmykane/quantified-self-lib#21]
The problem is in GXParser depend. which DOMParser is not included

(node:2030) UnhandledPromiseRejectionWarning: ReferenceError: DOMParser is not defined
    at GXParser (/mnt/c/greyp.workspace/playground/g6simulator/node_modules/gxparser/GXParser.js:40:16)
    at /mnt/c/greyp.workspace/playground/g6simulator/node_modules/quantified-self-lib/lib/events/adapters/importers/gpx/importer.gpx.js:34:29

**Comment by jimmykane** [comment]
Hey hi @isabolic , Indeed I think GPX parser was not made for Node (if I understand from the logs). 

I ll check this and create fix for this. 

However, I am in the middle of a big refactoring (will be using streams instead of points due to big data) and wanted to ask you how much will it cost if I have this fixed by the end of the year.....

**Comment by isabolic** [comment]
@jimmykane Hi,

no pressure, I have found a workaround.

Best regards
isabolic

**Comment by jimmykane** [comment]
2.2.4 fixes this
